### ISSUE TITLE
403 On Mesosphere Maven Repo

### ISSUE THREAD

**Issue by nightwolfzor** [mesosphere/chaos#23]
When hitting         <url>http://downloads.mesosphere.io/maven</url>
I'm getting a 403

**Comment by kolloch** [comment]
@lloesche is that intentional?

**Comment by lloesche** [comment]
@kolloch I'm afraid I don't know what's supposed to be served behind that URL, but since it's a public S3 bucket the default behaviour is to serve a 403 if the URL in question doesn't exist. I.e. there is no directory listing if that's what was expected.

Other URLs that are being used by maven like e.g. http://downloads.mesosphere.io/maven/mesosphere/chaos/maven-metadata.xml are being served however. So from a tools point of view everything should be working. It's just not setup for human browsing.

**Comment by kolloch** [comment]
Thanks @lloesche . Do you have problems using this repository, @nightwolfzor? 

Please elaborate if you cannot access the artefacts. Thanks!
